from ast import parse
from builtins import float

import easydict

class SSLTIE_args():
    def __init__(self):
        super().__init__()
        self.ssltie_args = easydict.EasyDict({
        'Flickr_trainset_path': '/',
        'Neg': True,
        'aud_aug': None,
        'audio_extract_batch_size': 256,
        'audio_mix_alpha': -1,
        'audio_mix_prob': -1,
        'audio_queue_size': 4000,
        'audio_replace_prob': -1.0,
        'batch_size': 64,
        'batch_trans_ratio': 0.3,
        'biCLLoss': False,
        'csv_path': '',
        'data_aug': True,
        'dataset_mode': 'Flickr',
        'debug': False,
        'epi_decay': False,
        'epoch': 1,
        'epochs': 80,
        'epsilon': 0.65,
        'epsilon2': 0.4,
        'equi_loss_type': 'mse',
        'eval_freq': 1,
        'eval_start': 10,
        'exp_name': 'vggss_train',
        'finetune_last_blocks': 2,
        'flow': False,
        'gpus': '0',
        'heatmap_no_grad': False,
        'heatmap_size': 14,
        'hostname': None,
        'image_size': 224,
        'img_aug': None,
        'lambda_rescale': 0.2,
        'lambda_trans_cl': 1.0,
        'lambda_trans_ts': 1.0,
        'learning_rate': 0.0001,
        'load_pretrain': False,
        'max_rotation_angle': 45,
        'mix_curri_end_epoch': 40,
        'mix_start_epoch': 1,
        'model_depth': 18,
        'model_name': 'vgg',
        'n_threads': 16,
        'normalisation': 'all',
        'obs_drop_fraction': 0.25,
        'obs_start_epoch': 5,
        'openset_70k': False,
        'pool': 'avgpool',
        'print_freq': 15,
        'rescale_factor': [0.85, 1.0],
        'rescale_prob': 0.8,
        'rescale_start_epoch': 5,
        'resume': '',
        'ret_seen_144k': False,
        'ret_start_epoch': 1,
        'retri_save_dir': 'assets/retri/',
        'seed': 4,
        'soundnet_test_path': '/mnt/lynx1/datasets/FlickrSoundNet/',
        'start_epoch': 1,
        'summaries_dir': 'ckpts/',
        'temperature': 0.07,
        'test': 'ckpts/ssltie_flickr.pth.tar',
        'test_csv': 'test.csv',
        'test_set': 'Flickr',
        'train_csv': 'train.csv',
        'training_set_scale': 'fullset',
        'trainset': 'VGGSS',
        'trainset_path': '/',
        'trans_equi_weight': 1.0,
        'tri_map': True,
        'val_set': 'VGGSS',
        'vggss_test_path': '/mnt/lynx1/datasets/VGGSound_v1/',
        'weight_decay': 0.0001,
        'write_summarys': True,
        })